# Generated by Django 3.2.13 on 2022-07-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20220713_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsession',
            name='session_date',
            field=models.DateField(null=True, verbose_name='Session date'),
        ),
        migrations.AlterField(
            model_name='studentsession',
            name='subject',
            field=models.CharField(choices=[('1', 'Milestone meeting 1'), ('2', 'Milestone meeting 2'), ('3', 'Milestone meeting 3')], default='1', help_text='Type of subject', max_length=1, verbose_name='Type of subject'),
        ),
        migrations.AlterField(
            model_name='studentsession',
            name='summary',
            field=models.TextField(help_text='Enter a summary of session with student', max_length=2000),
        ),
        migrations.AlterField(
            model_name='studentsession',
            name='type',
            field=models.CharField(choices=[('i', 'Introduction'), ('1', 'Milestone Proj. 1'), ('2', 'Milestone Proj. 2'), ('3', 'Milestone Proj. 3'), ('4', 'Milestone Proj. 4'), ('5', 'Milestone Proj. 5')], default='i', help_text='Type of session', max_length=1, verbose_name='Type of session'),
        ),
    ]
