# Generated by Django 3.2.13 on 2022-07-11 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_mentor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_program_start', models.DateField(blank=True, null=True, verbose_name='Program start date')),
                ('date_program_end', models.DateField(blank=True, null=True, verbose_name='Program end date')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentMentorCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, help_text='Enter a summary of Student overall progress from Mentor perspective.', max_length=2000)),
                ('mentor', models.ManyToManyField(help_text='Select Mentor for this student', to='dashboard.Mentor')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.student')),
            ],
        ),
    ]
