# Generated by Django 3.2.13 on 2022-07-11 14:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_student_studentmentorcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this session', primary_key=True, serialize=False)),
                ('summary', models.TextField(blank=True, help_text='Enter a summary of session with student', max_length=2000)),
                ('session_date', models.DateField(blank=True, null=True, verbose_name='Session date')),
                ('type', models.CharField(blank=True, choices=[('i', 'Introduction'), ('1', 'Milestone Proj. 1'), ('2', 'Milestone Proj. 2'), ('3', 'Milestone Proj. 3'), ('4', 'Milestone Proj. 4'), ('5', 'Milestone Proj. 5')], default='i', help_text='Type of session', max_length=1, verbose_name='Type of session')),
                ('subject', models.CharField(blank=True, choices=[('1', 'Milestone meeting 1'), ('2', 'Milestone meeting 2'), ('3', 'Milestone meeting 3')], default='1', help_text='Type of subject', max_length=1, verbose_name='Type of subject')),
                ('StudentMentorCard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='dashboard.studentmentorcard')),
            ],
            options={
                'ordering': ['session_date'],
            },
        ),
    ]
