# Generated by Django 3.2.13 on 2022-08-27 20:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20220819_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmentorcard',
            name='slack_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Slack name'),
        ),
        migrations.AddField(
            model_name='studentmentorcard',
            name='student_email',
            field=models.CharField(blank=True, max_length=200, verbose_name='Student email'),
        ),
        migrations.AddField(
            model_name='studentmentorcard',
            name='student_github',
            field=models.URLField(blank=True, verbose_name='Student GitHub'),
        ),
        migrations.AddField(
            model_name='studentmentorcard',
            name='student_linkedin',
            field=models.URLField(blank=True, verbose_name='Student linkedin'),
        ),
        migrations.CreateModel(
            name='MentorNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor_note', models.TextField(blank=True, help_text='A note on a Student', max_length=500)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('student_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.studentmentorcard')),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
    ]
